name: Build and push to dockerhub

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - name: find all Docker files
        # id: set-matrix
        # run: echo "::set-output name=matrix::$(ls * | jq -R -s -c 'split("\n")[:-1]')"
      - name: Build rust trunk image
        run: docker buildx build -t shawnyu5/rust-trunk - < Dockerfile-rust-trunk

      - name: login to dockerhub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: push rust truct image
        run: docker push shawnyu5/rust-trunk
